/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cassandrasidecar

import (
	"encoding/json"
)

// TruncateOperationRequest struct for TruncateOperationRequest
type TruncateOperationRequest struct {
	Type string `json:"type"`
	// keyspace to truncate
	Keyspace string `json:"keyspace"`
	// table to truncate
	Table string `json:"table"`
}

// NewTruncateOperationRequest instantiates a new TruncateOperationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTruncateOperationRequest(type_ string, keyspace string, table string, ) *TruncateOperationRequest {
	this := TruncateOperationRequest{}
	this.Type = type_
	this.Keyspace = keyspace
	this.Table = table
	return &this
}

// NewTruncateOperationRequestWithDefaults instantiates a new TruncateOperationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTruncateOperationRequestWithDefaults() *TruncateOperationRequest {
	this := TruncateOperationRequest{}
	return &this
}

// GetType returns the Type field value
func (o *TruncateOperationRequest) GetType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TruncateOperationRequest) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TruncateOperationRequest) SetType(v string) {
	o.Type = v
}

// GetKeyspace returns the Keyspace field value
func (o *TruncateOperationRequest) GetKeyspace() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Keyspace
}

// GetKeyspaceOk returns a tuple with the Keyspace field value
// and a boolean to check if the value has been set.
func (o *TruncateOperationRequest) GetKeyspaceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Keyspace, true
}

// SetKeyspace sets field value
func (o *TruncateOperationRequest) SetKeyspace(v string) {
	o.Keyspace = v
}

// GetTable returns the Table field value
func (o *TruncateOperationRequest) GetTable() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Table
}

// GetTableOk returns a tuple with the Table field value
// and a boolean to check if the value has been set.
func (o *TruncateOperationRequest) GetTableOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Table, true
}

// SetTable sets field value
func (o *TruncateOperationRequest) SetTable(v string) {
	o.Table = v
}

func (o TruncateOperationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["keyspace"] = o.Keyspace
	}
	if true {
		toSerialize["table"] = o.Table
	}
	return json.Marshal(toSerialize)
}

type NullableTruncateOperationRequest struct {
	value *TruncateOperationRequest
	isSet bool
}

func (v NullableTruncateOperationRequest) Get() *TruncateOperationRequest {
	return v.value
}

func (v *NullableTruncateOperationRequest) Set(val *TruncateOperationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTruncateOperationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTruncateOperationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTruncateOperationRequest(val *TruncateOperationRequest) *NullableTruncateOperationRequest {
	return &NullableTruncateOperationRequest{value: val, isSet: true}
}

func (v NullableTruncateOperationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTruncateOperationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
