/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cassandrasidecar

import (
	"encoding/json"
)

// RestoreOperationRequest struct for RestoreOperationRequest
type RestoreOperationRequest struct {
	// type of operation, one has to set it to 'restore' in case he wants this request to be considered as a backup one 
	Type string `json:"type"`
	// similar to field in backup request but used for telling from where files should be downloaded, not uploaded, in case globalRequest field is set to true, it does not matter what dc and node id is used, these components in storageLocation path will be automatically changed. 
	StorageLocation string `json:"storageLocation"`
	// similar to field in backup request but used for downloading files, not uploading them 
	ConcurrentConnections *int32 `json:"concurrentConnections,omitempty"`
	// similar to field in backup request 
	LockFile *string `json:"lockFile,omitempty"`
	// similar to field in backup request 
	CassandraDirectory *string `json:"cassandraDirectory,omitempty"`
	// directory where one expects to find 'conf/cassandra.yaml' file in case we need to update it with initial tokens in case restoration strategy is IN_PLACE. 
	CassandraConfigDirectory *string `json:"cassandraConfigDirectory,omitempty"`
	// a flag saying if we should restore system keyspaces as well, relevant only for IN_PLACE restoration 
	RestoreSystemKeyspace *bool `json:"restoreSystemKeyspace,omitempty"`
	// name of snapshot to restore 
	SnapshotTag string `json:"snapshotTag"`
	// similar to field in backup request, when empty, all entities in given snapshot will be restored 
	Entities *string `json:"entities,omitempty"`
	// flag telling if cassandra.yaml should be updated with initial_tokens, relevant only in case of IN_PLACE strategy 
	UpdateCassandraYaml *bool `json:"updateCassandraYaml,omitempty"`
	// strategy telling how we should go about restoration, please refer to details in backup and sidecar documentation 
	RestorationStrategyType *string `json:"restorationStrategyType,omitempty"`
	// phase telling what should we do, this field has to be set just once as DOWNLOAD if globalRequest if true and coordinator of that request will take care of all other phases automatically on its own 
	RestorationPhase *string `json:"restorationPhase,omitempty"`
	// flag saying if we should not delete truncated SSTables after they are imported, as part of CLEANUP phase, defaults to false 
	NoDeleteTruncates *bool `json:"noDeleteTruncates,omitempty"`
	// flag saying if we should not delete downloaded SSTables from remote location, as part of CLEANUP phase, defaults to false 
	NoDeleteDownloads *bool `json:"noDeleteDownloads,omitempty"`
	// flag saying if we should not download data from remote location as we expect them to be there already, defaults to false, setting this to true has sense only in case noDeleteDownloads was set to true in previous restoration requests 
	NoDownloadData *bool `json:"noDownloadData,omitempty"`
	// version of schema we want to restore from, upon backup, a schema version is automatically appended to snapshot name and its manifest is uploaded under that name. In case we have two snapshots having same name, we might distinguish between them by this schema version. If schema version is not specified, we expect that there will be one and only one backup taken with respective snapshot name. This schema version has to match the version of a Cassandra node we are doing restore for (hence, by proxy, when global request mode is used, all nodes have to be on exact same schema version). 
	SchemaVersion *string `json:"schemaVersion,omitempty"`
	// flag saying if we indeed want a schema version of a running node match with schema version a snapshot is taken on. there might be cases when we want to restore a table for which its CQL schema has not changed but it has changed for other table / keyspace but a schema for that node has changed by doing that. 
	ExactSchemaVersion *bool `json:"exactSchemaVersion,omitempty"`
	Import *ImportOperationRequest `json:"import,omitempty"`
	// flag saying that this request is a global one, meaning that a Sidecar this request is sent to will act as a restoration coordinator sending all other requests to each node in a cluster, for each phase. 
	GlobalRequest *bool `json:"globalRequest,omitempty"`
}

// NewRestoreOperationRequest instantiates a new RestoreOperationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestoreOperationRequest(type_ string, storageLocation string, snapshotTag string, ) *RestoreOperationRequest {
	this := RestoreOperationRequest{}
	this.Type = type_
	this.StorageLocation = storageLocation
	this.SnapshotTag = snapshotTag
	return &this
}

// NewRestoreOperationRequestWithDefaults instantiates a new RestoreOperationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestoreOperationRequestWithDefaults() *RestoreOperationRequest {
	this := RestoreOperationRequest{}
	return &this
}

// GetType returns the Type field value
func (o *RestoreOperationRequest) GetType() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RestoreOperationRequest) SetType(v string) {
	o.Type = v
}

// GetStorageLocation returns the StorageLocation field value
func (o *RestoreOperationRequest) GetStorageLocation() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.StorageLocation
}

// GetStorageLocationOk returns a tuple with the StorageLocation field value
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetStorageLocationOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.StorageLocation, true
}

// SetStorageLocation sets field value
func (o *RestoreOperationRequest) SetStorageLocation(v string) {
	o.StorageLocation = v
}

// GetConcurrentConnections returns the ConcurrentConnections field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetConcurrentConnections() int32 {
	if o == nil || o.ConcurrentConnections == nil {
		var ret int32
		return ret
	}
	return *o.ConcurrentConnections
}

// GetConcurrentConnectionsOk returns a tuple with the ConcurrentConnections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetConcurrentConnectionsOk() (*int32, bool) {
	if o == nil || o.ConcurrentConnections == nil {
		return nil, false
	}
	return o.ConcurrentConnections, true
}

// HasConcurrentConnections returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasConcurrentConnections() bool {
	if o != nil && o.ConcurrentConnections != nil {
		return true
	}

	return false
}

// SetConcurrentConnections gets a reference to the given int32 and assigns it to the ConcurrentConnections field.
func (o *RestoreOperationRequest) SetConcurrentConnections(v int32) {
	o.ConcurrentConnections = &v
}

// GetLockFile returns the LockFile field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetLockFile() string {
	if o == nil || o.LockFile == nil {
		var ret string
		return ret
	}
	return *o.LockFile
}

// GetLockFileOk returns a tuple with the LockFile field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetLockFileOk() (*string, bool) {
	if o == nil || o.LockFile == nil {
		return nil, false
	}
	return o.LockFile, true
}

// HasLockFile returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasLockFile() bool {
	if o != nil && o.LockFile != nil {
		return true
	}

	return false
}

// SetLockFile gets a reference to the given string and assigns it to the LockFile field.
func (o *RestoreOperationRequest) SetLockFile(v string) {
	o.LockFile = &v
}

// GetCassandraDirectory returns the CassandraDirectory field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetCassandraDirectory() string {
	if o == nil || o.CassandraDirectory == nil {
		var ret string
		return ret
	}
	return *o.CassandraDirectory
}

// GetCassandraDirectoryOk returns a tuple with the CassandraDirectory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetCassandraDirectoryOk() (*string, bool) {
	if o == nil || o.CassandraDirectory == nil {
		return nil, false
	}
	return o.CassandraDirectory, true
}

// HasCassandraDirectory returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasCassandraDirectory() bool {
	if o != nil && o.CassandraDirectory != nil {
		return true
	}

	return false
}

// SetCassandraDirectory gets a reference to the given string and assigns it to the CassandraDirectory field.
func (o *RestoreOperationRequest) SetCassandraDirectory(v string) {
	o.CassandraDirectory = &v
}

// GetCassandraConfigDirectory returns the CassandraConfigDirectory field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetCassandraConfigDirectory() string {
	if o == nil || o.CassandraConfigDirectory == nil {
		var ret string
		return ret
	}
	return *o.CassandraConfigDirectory
}

// GetCassandraConfigDirectoryOk returns a tuple with the CassandraConfigDirectory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetCassandraConfigDirectoryOk() (*string, bool) {
	if o == nil || o.CassandraConfigDirectory == nil {
		return nil, false
	}
	return o.CassandraConfigDirectory, true
}

// HasCassandraConfigDirectory returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasCassandraConfigDirectory() bool {
	if o != nil && o.CassandraConfigDirectory != nil {
		return true
	}

	return false
}

// SetCassandraConfigDirectory gets a reference to the given string and assigns it to the CassandraConfigDirectory field.
func (o *RestoreOperationRequest) SetCassandraConfigDirectory(v string) {
	o.CassandraConfigDirectory = &v
}

// GetRestoreSystemKeyspace returns the RestoreSystemKeyspace field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetRestoreSystemKeyspace() bool {
	if o == nil || o.RestoreSystemKeyspace == nil {
		var ret bool
		return ret
	}
	return *o.RestoreSystemKeyspace
}

// GetRestoreSystemKeyspaceOk returns a tuple with the RestoreSystemKeyspace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetRestoreSystemKeyspaceOk() (*bool, bool) {
	if o == nil || o.RestoreSystemKeyspace == nil {
		return nil, false
	}
	return o.RestoreSystemKeyspace, true
}

// HasRestoreSystemKeyspace returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasRestoreSystemKeyspace() bool {
	if o != nil && o.RestoreSystemKeyspace != nil {
		return true
	}

	return false
}

// SetRestoreSystemKeyspace gets a reference to the given bool and assigns it to the RestoreSystemKeyspace field.
func (o *RestoreOperationRequest) SetRestoreSystemKeyspace(v bool) {
	o.RestoreSystemKeyspace = &v
}

// GetSnapshotTag returns the SnapshotTag field value
func (o *RestoreOperationRequest) GetSnapshotTag() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.SnapshotTag
}

// GetSnapshotTagOk returns a tuple with the SnapshotTag field value
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetSnapshotTagOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SnapshotTag, true
}

// SetSnapshotTag sets field value
func (o *RestoreOperationRequest) SetSnapshotTag(v string) {
	o.SnapshotTag = v
}

// GetEntities returns the Entities field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetEntities() string {
	if o == nil || o.Entities == nil {
		var ret string
		return ret
	}
	return *o.Entities
}

// GetEntitiesOk returns a tuple with the Entities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetEntitiesOk() (*string, bool) {
	if o == nil || o.Entities == nil {
		return nil, false
	}
	return o.Entities, true
}

// HasEntities returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasEntities() bool {
	if o != nil && o.Entities != nil {
		return true
	}

	return false
}

// SetEntities gets a reference to the given string and assigns it to the Entities field.
func (o *RestoreOperationRequest) SetEntities(v string) {
	o.Entities = &v
}

// GetUpdateCassandraYaml returns the UpdateCassandraYaml field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetUpdateCassandraYaml() bool {
	if o == nil || o.UpdateCassandraYaml == nil {
		var ret bool
		return ret
	}
	return *o.UpdateCassandraYaml
}

// GetUpdateCassandraYamlOk returns a tuple with the UpdateCassandraYaml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetUpdateCassandraYamlOk() (*bool, bool) {
	if o == nil || o.UpdateCassandraYaml == nil {
		return nil, false
	}
	return o.UpdateCassandraYaml, true
}

// HasUpdateCassandraYaml returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasUpdateCassandraYaml() bool {
	if o != nil && o.UpdateCassandraYaml != nil {
		return true
	}

	return false
}

// SetUpdateCassandraYaml gets a reference to the given bool and assigns it to the UpdateCassandraYaml field.
func (o *RestoreOperationRequest) SetUpdateCassandraYaml(v bool) {
	o.UpdateCassandraYaml = &v
}

// GetRestorationStrategyType returns the RestorationStrategyType field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetRestorationStrategyType() string {
	if o == nil || o.RestorationStrategyType == nil {
		var ret string
		return ret
	}
	return *o.RestorationStrategyType
}

// GetRestorationStrategyTypeOk returns a tuple with the RestorationStrategyType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetRestorationStrategyTypeOk() (*string, bool) {
	if o == nil || o.RestorationStrategyType == nil {
		return nil, false
	}
	return o.RestorationStrategyType, true
}

// HasRestorationStrategyType returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasRestorationStrategyType() bool {
	if o != nil && o.RestorationStrategyType != nil {
		return true
	}

	return false
}

// SetRestorationStrategyType gets a reference to the given string and assigns it to the RestorationStrategyType field.
func (o *RestoreOperationRequest) SetRestorationStrategyType(v string) {
	o.RestorationStrategyType = &v
}

// GetRestorationPhase returns the RestorationPhase field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetRestorationPhase() string {
	if o == nil || o.RestorationPhase == nil {
		var ret string
		return ret
	}
	return *o.RestorationPhase
}

// GetRestorationPhaseOk returns a tuple with the RestorationPhase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetRestorationPhaseOk() (*string, bool) {
	if o == nil || o.RestorationPhase == nil {
		return nil, false
	}
	return o.RestorationPhase, true
}

// HasRestorationPhase returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasRestorationPhase() bool {
	if o != nil && o.RestorationPhase != nil {
		return true
	}

	return false
}

// SetRestorationPhase gets a reference to the given string and assigns it to the RestorationPhase field.
func (o *RestoreOperationRequest) SetRestorationPhase(v string) {
	o.RestorationPhase = &v
}

// GetNoDeleteTruncates returns the NoDeleteTruncates field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetNoDeleteTruncates() bool {
	if o == nil || o.NoDeleteTruncates == nil {
		var ret bool
		return ret
	}
	return *o.NoDeleteTruncates
}

// GetNoDeleteTruncatesOk returns a tuple with the NoDeleteTruncates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetNoDeleteTruncatesOk() (*bool, bool) {
	if o == nil || o.NoDeleteTruncates == nil {
		return nil, false
	}
	return o.NoDeleteTruncates, true
}

// HasNoDeleteTruncates returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasNoDeleteTruncates() bool {
	if o != nil && o.NoDeleteTruncates != nil {
		return true
	}

	return false
}

// SetNoDeleteTruncates gets a reference to the given bool and assigns it to the NoDeleteTruncates field.
func (o *RestoreOperationRequest) SetNoDeleteTruncates(v bool) {
	o.NoDeleteTruncates = &v
}

// GetNoDeleteDownloads returns the NoDeleteDownloads field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetNoDeleteDownloads() bool {
	if o == nil || o.NoDeleteDownloads == nil {
		var ret bool
		return ret
	}
	return *o.NoDeleteDownloads
}

// GetNoDeleteDownloadsOk returns a tuple with the NoDeleteDownloads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetNoDeleteDownloadsOk() (*bool, bool) {
	if o == nil || o.NoDeleteDownloads == nil {
		return nil, false
	}
	return o.NoDeleteDownloads, true
}

// HasNoDeleteDownloads returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasNoDeleteDownloads() bool {
	if o != nil && o.NoDeleteDownloads != nil {
		return true
	}

	return false
}

// SetNoDeleteDownloads gets a reference to the given bool and assigns it to the NoDeleteDownloads field.
func (o *RestoreOperationRequest) SetNoDeleteDownloads(v bool) {
	o.NoDeleteDownloads = &v
}

// GetNoDownloadData returns the NoDownloadData field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetNoDownloadData() bool {
	if o == nil || o.NoDownloadData == nil {
		var ret bool
		return ret
	}
	return *o.NoDownloadData
}

// GetNoDownloadDataOk returns a tuple with the NoDownloadData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetNoDownloadDataOk() (*bool, bool) {
	if o == nil || o.NoDownloadData == nil {
		return nil, false
	}
	return o.NoDownloadData, true
}

// HasNoDownloadData returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasNoDownloadData() bool {
	if o != nil && o.NoDownloadData != nil {
		return true
	}

	return false
}

// SetNoDownloadData gets a reference to the given bool and assigns it to the NoDownloadData field.
func (o *RestoreOperationRequest) SetNoDownloadData(v bool) {
	o.NoDownloadData = &v
}

// GetSchemaVersion returns the SchemaVersion field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetSchemaVersion() string {
	if o == nil || o.SchemaVersion == nil {
		var ret string
		return ret
	}
	return *o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetSchemaVersionOk() (*string, bool) {
	if o == nil || o.SchemaVersion == nil {
		return nil, false
	}
	return o.SchemaVersion, true
}

// HasSchemaVersion returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasSchemaVersion() bool {
	if o != nil && o.SchemaVersion != nil {
		return true
	}

	return false
}

// SetSchemaVersion gets a reference to the given string and assigns it to the SchemaVersion field.
func (o *RestoreOperationRequest) SetSchemaVersion(v string) {
	o.SchemaVersion = &v
}

// GetExactSchemaVersion returns the ExactSchemaVersion field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetExactSchemaVersion() bool {
	if o == nil || o.ExactSchemaVersion == nil {
		var ret bool
		return ret
	}
	return *o.ExactSchemaVersion
}

// GetExactSchemaVersionOk returns a tuple with the ExactSchemaVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetExactSchemaVersionOk() (*bool, bool) {
	if o == nil || o.ExactSchemaVersion == nil {
		return nil, false
	}
	return o.ExactSchemaVersion, true
}

// HasExactSchemaVersion returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasExactSchemaVersion() bool {
	if o != nil && o.ExactSchemaVersion != nil {
		return true
	}

	return false
}

// SetExactSchemaVersion gets a reference to the given bool and assigns it to the ExactSchemaVersion field.
func (o *RestoreOperationRequest) SetExactSchemaVersion(v bool) {
	o.ExactSchemaVersion = &v
}

// GetImport returns the Import field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetImport() ImportOperationRequest {
	if o == nil || o.Import == nil {
		var ret ImportOperationRequest
		return ret
	}
	return *o.Import
}

// GetImportOk returns a tuple with the Import field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetImportOk() (*ImportOperationRequest, bool) {
	if o == nil || o.Import == nil {
		return nil, false
	}
	return o.Import, true
}

// HasImport returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasImport() bool {
	if o != nil && o.Import != nil {
		return true
	}

	return false
}

// SetImport gets a reference to the given ImportOperationRequest and assigns it to the Import field.
func (o *RestoreOperationRequest) SetImport(v ImportOperationRequest) {
	o.Import = &v
}

// GetGlobalRequest returns the GlobalRequest field value if set, zero value otherwise.
func (o *RestoreOperationRequest) GetGlobalRequest() bool {
	if o == nil || o.GlobalRequest == nil {
		var ret bool
		return ret
	}
	return *o.GlobalRequest
}

// GetGlobalRequestOk returns a tuple with the GlobalRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreOperationRequest) GetGlobalRequestOk() (*bool, bool) {
	if o == nil || o.GlobalRequest == nil {
		return nil, false
	}
	return o.GlobalRequest, true
}

// HasGlobalRequest returns a boolean if a field has been set.
func (o *RestoreOperationRequest) HasGlobalRequest() bool {
	if o != nil && o.GlobalRequest != nil {
		return true
	}

	return false
}

// SetGlobalRequest gets a reference to the given bool and assigns it to the GlobalRequest field.
func (o *RestoreOperationRequest) SetGlobalRequest(v bool) {
	o.GlobalRequest = &v
}

func (o RestoreOperationRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["storageLocation"] = o.StorageLocation
	}
	if o.ConcurrentConnections != nil {
		toSerialize["concurrentConnections"] = o.ConcurrentConnections
	}
	if o.LockFile != nil {
		toSerialize["lockFile"] = o.LockFile
	}
	if o.CassandraDirectory != nil {
		toSerialize["cassandraDirectory"] = o.CassandraDirectory
	}
	if o.CassandraConfigDirectory != nil {
		toSerialize["cassandraConfigDirectory"] = o.CassandraConfigDirectory
	}
	if o.RestoreSystemKeyspace != nil {
		toSerialize["restoreSystemKeyspace"] = o.RestoreSystemKeyspace
	}
	if true {
		toSerialize["snapshotTag"] = o.SnapshotTag
	}
	if o.Entities != nil {
		toSerialize["entities"] = o.Entities
	}
	if o.UpdateCassandraYaml != nil {
		toSerialize["updateCassandraYaml"] = o.UpdateCassandraYaml
	}
	if o.RestorationStrategyType != nil {
		toSerialize["restorationStrategyType"] = o.RestorationStrategyType
	}
	if o.RestorationPhase != nil {
		toSerialize["restorationPhase"] = o.RestorationPhase
	}
	if o.NoDeleteTruncates != nil {
		toSerialize["noDeleteTruncates"] = o.NoDeleteTruncates
	}
	if o.NoDeleteDownloads != nil {
		toSerialize["noDeleteDownloads"] = o.NoDeleteDownloads
	}
	if o.NoDownloadData != nil {
		toSerialize["noDownloadData"] = o.NoDownloadData
	}
	if o.SchemaVersion != nil {
		toSerialize["schemaVersion"] = o.SchemaVersion
	}
	if o.ExactSchemaVersion != nil {
		toSerialize["exactSchemaVersion"] = o.ExactSchemaVersion
	}
	if o.Import != nil {
		toSerialize["import"] = o.Import
	}
	if o.GlobalRequest != nil {
		toSerialize["globalRequest"] = o.GlobalRequest
	}
	return json.Marshal(toSerialize)
}

type NullableRestoreOperationRequest struct {
	value *RestoreOperationRequest
	isSet bool
}

func (v NullableRestoreOperationRequest) Get() *RestoreOperationRequest {
	return v.value
}

func (v *NullableRestoreOperationRequest) Set(val *RestoreOperationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRestoreOperationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRestoreOperationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestoreOperationRequest(val *RestoreOperationRequest) *NullableRestoreOperationRequest {
	return &NullableRestoreOperationRequest{value: val, isSet: true}
}

func (v NullableRestoreOperationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestoreOperationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
